import React from 'react';
import { ArrowRight, CheckCircle2, MessageCircle } from 'lucide-react';
import { whatsappLink } from '../../data/contact';

const stages = [
  ['Elegir la estructura', 'Conversamos sobre tu actividad, tus socios y la forma de organización que estás considerando.'],
  ['Preparar la constitución', 'Revisamos la documentación y los trámites que correspondan al tipo de sociedad y jurisdicción.'],
  ['Organizar la operación', 'Podemos acompañarte después con altas impositivas, contabilidad y liquidación de sueldos.'],
];

const CompanyCreationSection = () => <>
  <section className="relative overflow-hidden bg-primary-900 py-20 text-white md:py-28"><div className="absolute -right-24 top-0 h-96 w-96 rounded-full border border-white/10" aria-hidden="true" /><div className="container relative mx-auto grid items-center gap-12 px-6 lg:grid-cols-2"><div><p className="mb-4 text-sm font-bold uppercase tracking-[0.18em] text-accent-300">Para emprendedores y empresas</p><h1 className="mb-6 text-4xl font-bold leading-tight md:text-5xl">Dale una estructura sólida a tu próximo proyecto</h1><p className="mb-8 max-w-xl text-lg leading-relaxed text-primary-100">Constituir una sociedad implica elegir una forma de organización, reunir documentación y realizar trámites. Te orientamos en cada etapa y podemos acompañarte también cuando tu empresa comience a operar.</p><a href={whatsappLink('Hola, quisiera consultar por la constitución de una sociedad.')} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-accent-500 px-7 py-4 font-bold text-white hover:bg-accent-600"><MessageCircle size={20} /> Consultar por mi proyecto</a></div><div className="rounded-3xl border border-white/15 bg-white/10 p-8"><p className="mb-5 text-sm font-bold uppercase tracking-widest text-accent-300">Podemos conversar sobre</p>{['Sociedad de Responsabilidad Limitada (SRL)', 'Sociedad Anónima (SA)', 'Sociedad por Acciones Simplificada (SAS)'].map(item => <p key={item} className="flex items-start gap-3 border-b border-white/10 py-4 text-lg"><CheckCircle2 size={22} className="mt-1 shrink-0 text-accent-300" />{item}</p>)}<p className="mt-5 text-sm leading-relaxed text-primary-100">La opción y los trámites aplicables se analizan según tu caso.</p></div></div></section>
  <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-6"><div className="mb-12 max-w-2xl"><p className="mb-3 text-sm font-bold uppercase tracking-[0.18em] text-accent-600">Cómo te acompañamos</p><h2 className="text-3xl font-bold text-primary-900 md:text-4xl">Del proyecto a la operación</h2><p className="mt-4 text-lg text-gray-600">La consulta inicial nos permite entender tu situación y definir qué parte del proceso necesitás delegar.</p></div><div className="grid gap-6 md:grid-cols-3">{stages.map(([title, text], index) => <article className="rounded-2xl border border-primary-100 bg-primary-50 p-7" key={title}><span className="mb-5 block text-sm font-bold text-accent-700">PASO 0{index + 1}</span><h3 className="mb-3 text-xl font-bold text-primary-900">{title}</h3><p className="leading-relaxed text-gray-600">{text}</p></article>)}</div><div className="mt-12 rounded-2xl bg-primary-900 p-8 text-white md:flex md:items-center md:justify-between md:gap-8"><div><h2 className="text-2xl font-bold">¿Ya tenés una idea en marcha?</h2><p className="mt-2 text-primary-100">Contanos qué actividad querés desarrollar y en qué etapa estás.</p></div><a href={whatsappLink('Hola, quiero consultar por la creación de una sociedad. Mi proyecto es: ')} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex shrink-0 items-center gap-2 rounded-lg bg-accent-500 px-6 py-4 font-bold hover:bg-accent-600 md:mt-0">Escribir al estudio <ArrowRight size={19} /></a></div></div></section>
</>;
export default CompanyCreationSection;
