import React from 'react';
import { Clock, Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { Link } from 'react-router-dom';
import { email, phoneDisplay, phoneHref, whatsappLink } from '../../data/contact';

const ContactSection = ({ compact = false }) => <section id="contacto" className="bg-primary-50 py-20 md:py-24"><div className="container mx-auto px-6"><div className="grid overflow-hidden rounded-3xl bg-white shadow-xl lg:grid-cols-2">
  <div className="bg-primary-900 p-9 text-white md:p-12"><p className="mb-3 text-sm font-bold uppercase tracking-[0.18em] text-accent-300">Estamos para ayudarte</p><h2 className="mb-5 text-3xl font-bold md:text-4xl">Contanos qué necesitás resolver</h2><p className="max-w-lg leading-relaxed text-primary-100">Podés escribirnos por WhatsApp o dejar una consulta breve para que el estudio la reciba ordenada. Para orientarte mejor, contanos tu actividad y si tenés un vencimiento cercano.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/contacto" className="inline-flex items-center gap-2 rounded-lg bg-accent-500 px-6 py-4 font-bold text-white transition hover:bg-accent-600"><Mail size={20} /> Dejar una consulta</Link><a href={whatsappLink()} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-white/40 px-6 py-4 font-bold text-white transition hover:bg-white/10"><MessageCircle size={20} /> Escribir por WhatsApp</a></div></div>
  <div className="grid content-center gap-7 p-9 md:p-12"><h3 className="text-xl font-bold text-primary-900">Otras formas de contacto</h3><a href={phoneHref} className="flex items-start gap-4 text-primary-900 hover:text-accent-700"><Phone className="mt-1 shrink-0 text-accent-600" /><span><strong className="block">Teléfono</strong>{phoneDisplay}</span></a><a href={`mailto:${email}`} className="flex items-start gap-4 break-all text-primary-900 hover:text-accent-700"><Mail className="mt-1 shrink-0 text-accent-600" /><span><strong className="block">Correo electrónico</strong>{email}</span></a><div className="flex items-start gap-4 text-primary-900"><MapPin className="mt-1 shrink-0 text-accent-600" /><span><strong className="block">Ubicación</strong>Parque Patricios, CABA</span></div><div className="flex items-start gap-4 text-primary-900"><Clock className="mt-1 shrink-0 text-accent-600" /><span><strong className="block">Horario de atención</strong>Lunes a viernes · 9:30 a 18:00</span></div>{!compact && <p className="border-t border-primary-100 pt-5 text-sm text-gray-600">Si tenés una fecha de vencimiento cercana, mencionála en tu mensaje.</p>}</div>
</div></div></section>;
export default ContactSection;
