import React from 'react';
import { ArrowRight, Instagram, Mail, MessageCircle } from 'lucide-react';
import { Link } from 'react-router-dom';

const resources = [
  { title: '¿Qué contar en una primera consulta?', text: 'Tu actividad, el tema que querés resolver y si tenés un vencimiento cercano. Con esa información podemos orientarte mejor.', icon: MessageCircle },
  { title: '¿Qué documentación puede ser útil?', text: 'Depende de la consulta. En general, conviene tener a mano constancias de inscripción y comunicaciones recientes del organismo correspondiente.', icon: Mail },
];
const NewsSection = () => <section className="bg-primary-50 py-20 md:py-24"><div className="container mx-auto px-6"><div className="mb-12 max-w-2xl"><p className="mb-3 text-sm font-bold uppercase tracking-[0.18em] text-accent-600">Información para empezar</p><h2 className="text-3xl font-bold text-primary-900 md:text-4xl">Recursos y novedades</h2><p className="mt-4 text-lg text-gray-600">Algunas respuestas prácticas para preparar tu consulta. Compartimos novedades del estudio en Instagram.</p></div><div className="grid gap-6 md:grid-cols-2">{resources.map(({ title, text, icon: Icon }) => <article key={title} className="rounded-2xl bg-white p-8 shadow-sm">{React.createElement(Icon, { className: 'mb-6 text-accent-600', size: 31 })}<h3 className="mb-3 text-xl font-bold text-primary-900">{title}</h3><p className="leading-relaxed text-gray-600">{text}</p></article>)}</div><div className="mt-9 flex flex-wrap gap-4"><a href="https://www.instagram.com/abm.estudiocontable/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-primary-900 px-6 py-4 font-bold text-white hover:bg-primary-800"><Instagram size={20} /> Seguir en Instagram</a><Link to="/contacto" className="inline-flex items-center gap-2 rounded-lg border border-primary-900 px-6 py-4 font-bold text-primary-900 hover:bg-white">Hacer una consulta <ArrowRight size={19} /></Link></div></div></section>;
export default NewsSection;
